module.exports = {
  'establishment-application': 'PEL applications',
  'establishment-revoke': 'PEL revocations',
  'establishment-grant': 'PEL applications',
  'establishment-update': 'PEL detail amendments',
  'legacy-project-application': 'Legacy PPL applications',
  'legacy-project-amendment': 'Legacy PPL amendments',
  'legacy-project-revoke': 'Legacy PPL revocations',
  'legacy-project-transfer': 'Legacy PPL transfers',
  'project-application': 'PPL applications',
  'project-amendment': 'PPL amendments',
  'project-revoke': 'PPL revocations',
  'project-transfer': 'PPL transfers',
  'pil-application': 'PIL applications',
  'pil-amendment': 'PIL amendments',
  'pil-revoke': 'PIL revocations',
  'pil-transfer': 'PIL transfers',
  'pil-review': 'PIL reviews',
  'role-create': 'Named people assignments',
  'role-delete': 'Named people removals',
  'place-update': 'Approved area amendments',
  'place-create': 'Approved area additions',
  'place-delete': 'Approved area deletions',
  'profile-update': 'Profile updates'
};
