module.exports = {
  buttons: {
    submit: 'Update'
  },
  pageTitle: 'Performance metrics',
  'establishment-application': 'PEL applications',
  'establishment-revoke': 'PEL revocations',
  'legacy-project-application': 'PPL applications',
  'legacy-project-amendment': 'PPL amendments',
  'legacy-project-change-licence-holder': 'PPL holder change',
  'legacy-project-revoke': 'PPL revocations',
  'legacy-project-transfer': 'PPL transfers',
  'legacy-project-expiry': 'PPL expirations',
  'project-application': 'PPL applications',
  'project-amendment': 'PPL amendments',
  'project-change-licence-holder': 'PPL holder change',
  'project-revoke': 'PPL revocations',
  'project-transfer': 'PPL transfers',
  'project-expiry': 'PPL expirations',
  'project-grant-ra': 'Retrospective assessments completed',
  'all-project-application': 'PPL applications',
  'all-project-amendment': 'PPL amendments',
  'all-project-change-licence-holder': 'PPL holder change',
  'all-project-revoke': 'PPL revocations',
  'all-project-transfer': 'PPL transfers',
  'all-project-expiry': 'PPL expirations',
  'pil-application': 'PIL applications',
  'pil-amendment': 'PIL amendments',
  'pil-revoke': 'PIL revocations',
  'pil-transfer': 'PIL transfers',
  'pil-review': 'PIL reviews',
  'rop-submit': 'Rop submissions',
  'establishment-grant': 'PEL applications',
  'establishment-update': 'PEL detail amendments',
  'role-create': 'Named people assignments',
  'role-delete': 'Named people removals',
  'place-update': 'Approved area amendments',
  'place-create': 'Approved area additions',
  'place-delete': 'Approved area deletions',
  date: {
    all: 'All',
    week: 'This week',
    month: 'This month',
    year: 'This year'
  }
};
