module.exports = {
  pageTitle: 'Performance metrics',
  'establishment-application': 'PEL applications',
  'establishment-revoke': 'PEL revocations',
  'legacy-project-application': 'PPL applications (Legacy)',
  'legacy-project-amendment': 'PPL amendments (Legacy)',
  'legacy-project-revoke': 'PPL revocations (Legacy)',
  'legacy-project-transfer': 'PPL transfers (Legacy)',
  'project-application': 'PPL applications (New)',
  'project-amendment': 'PPL amendments (New)',
  'project-revoke': 'PPL revocations (New)',
  'project-transfer': 'PPL transfers (New)',
  'pil-application': 'PIL applications',
  'pil-amendment': 'PIL amendments',
  'pil-revoke': 'PIL revocations',
  'pil-transfer': 'PIL transfers',
  'pil-review': 'PIL reviews',
  'trainingPil-application': 'Cat E PIL applications',
  'trainingPil-revoke': 'Cat E PIL revocations',
  'role-create': 'Named people assignments',
  'role-delete': 'Named people revocations',
  'place-update': 'Approved area amendments',
  'place-create': 'Approved area additions',
  'place-delete': 'Approved area deletions',
  'profile-update': 'Profile updates',
  date: {
    all: 'All',
    week: 'This week',
    month: 'This month',
    year: 'This year'
  }
};
